### ISSUE TITLE
Organizing References Page 

### ISSUE THREAD

**Issue by olbeck** [Nonprofit-Open-Data-Collective/compensator#16]
I tried to add the following code to the end of the _pkgdown.yml

```
reference:
  - title: Appraisal Process 
    contents:
    - calc_distance
    - dat_filtering
    - get_appraisal
    - get_geo_dist
    - get_geo_weights
    - get_mission_dist
    - get_mission_weights
    - get_org_values
    - get_salary_range
    - get_weights
    - predict_salary
    - select_sample
  - title: Data
    contents:
    - nonprofits
    - nonprofits.detailed
    - ntee.crosswalk
    - ntee.orig
    - state.abb52
    - state.dist.mat
  - title: NTEE Codes
    contents:
    - get_new_ntee
  - title: Miscellaneous
    contents:
    - dollarize
```

And I get the following error when building the reference page: 

<img width="569" alt="Screenshot 2023-05-05 at 11 58 08 AM" src="https://user-images.githubusercontent.com/55454718/236508081-0ce5d70d-335b-4992-886a-34182fd5f631.png">

I tried adding `@keywords` in the roxygen comments of calc_distance.R but the same error happened.

I looked at the documentation for building the reference page [here](https://pkgdown.r-lib.org/reference/build_reference.html) which says 
<img width="787" alt="Screenshot 2023-05-05 at 12 02 25 PM" src="https://user-images.githubusercontent.com/55454718/236509028-96f1296e-d0a0-4102-bd61-f045b30eeaaf.png">

I am using the exact function names. I do not know why this error is occurring.
